using System.Numerics;

namespace MechFFBReader.Events;

/// <summary>
/// Event fired when a weapon is discharged
/// </summary>
public class WeaponFireEvent : TelemetryEvent
{
    public override string EventType => "WeaponFire";
    
    /// <summary>
    /// Type of weapon (AC/2, AC/5, AC/10, AC/20, Laser, PPC, etc.)
    /// </summary>
    public string WeaponType { get; set; } = string.Empty;
    
    /// <summary>
    /// Weapon class: Ballistic, Energy, Missile, Melee
    /// </summary>
    public WeaponClass WeaponClass { get; set; }
    
    /// <summary>
    /// Damage per shot/volley
    /// </summary>
    public float Damage { get; set; }
    
    /// <summary>
    /// Projectile mass (for ballistics) in tons
    /// </summary>
    public float ProjectileMass { get; set; }
    
    /// <summary>
    /// Muzzle velocity (for ballistics) in m/s
    /// </summary>
    public float MuzzleVelocity { get; set; }
    
    /// <summary>
    /// Heat generated by the weapon
    /// </summary>
    public float HeatGenerated { get; set; }
    
    /// <summary>
    /// Number of projectiles/missiles in this volley
    /// </summary>
    public int ProjectileCount { get; set; } = 1;
    
    /// <summary>
    /// Weapon mount location (arm, torso, etc.)
    /// </summary>
    public string MountLocation { get; set; } = string.Empty;
    
    /// <summary>
    /// Direction the weapon was facing when fired (for recoil calculation)
    /// </summary>
    public Vector3 FiringDirection { get; set; }
    
    /// <summary>
    /// Is this weapon mounted in an arm that can be aimed independently?
    /// </summary>
    public bool IsArmMounted { get; set; }
    
    /// <summary>
    /// Is this a PPC (vs laser/flamer/MG for Energy weapons)?
    /// </summary>
    public bool IsPPC { get; set; }
    
    /// <summary>
    /// Is this a machine gun (rapid fire weapon)?
    /// </summary>
    public bool IsMachineGun { get; set; }
    
    /// <summary>
    /// Is this weapon currently active/firing? (for continuous weapons like lasers/MGs)
    /// </summary>
    public bool IsActive { get; set; }
    
    /// <summary>
    /// Beam/firing duration in seconds (for lasers - from F3)
    /// </summary>
    public float BeamDuration { get; set; }
    
    /// <summary>
    /// Delay between missiles in seconds (for streak missiles - from F1)
    /// </summary>
    public float FiringDelay { get; set; }
}

public enum WeaponClass
{
    Ballistic,
    Energy,
    Missile,
    Melee,
    AMS  // Anti-Missile System
}
